config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'themes#index'
  resources :themes do
    collection do
      get 'decision/:id' => 'themes#decision'
      get 'decision_candidate'
      get 'post_theme'
    end
  end

end

app/models/theme.rb
class Theme < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def index
    @themes = Theme.all
  end

  def create
    @theme = Theme.new(theme_params)
    @theme.status = 'todo'
    @theme.save
    redirect_to action: :index
  end

  def decision_candidate
    themes = Theme.where("status = ?",'todo')
    theme_num = rand(themes.count)
    @theme = themes[theme_num]
    @decision_candidate = Theme.new
  end

  def decision
    @theme = Theme.find(params[:id])
    @decision_theme = @theme
    @theme.delete
  end

  def post_theme
    @theme = Theme.new
  end

  private

  def theme_params
    params.require(:theme).permit(:title, :content, :kind)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koreyaro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="title">
    <%= link_to "Koreyaro", themes_path %><i class="fa fa-pencil"></i>
  </div>
  <div class="select-action">
    <div class="post">
    <%= link_to "投稿する", action: :post_theme %>
    </div>
    <div class="decision">
    <%= link_to "テーマを決定する", action: :decision_candidate %>
    </div>
  </div>
</header>

<div class="contents">
<%= yield %>
</div>

</body>
</html>

app/views/themes/decision.html.slim
.theme-decision
   = p "#{@decision_theme.title}で決定しました"
= link_to "テーマ一覧に戻る",action: :index

app/views/themes/decision_candidate.html.slim
.theme-decision
  - if @theme.present?
    h2 = @theme.title
    p = @theme.kind
    p = @theme.content
    = form_tag("/themes/decision/#{@theme.id}", method: :get)
      = submit_tag "決定"
  - else
    | テーマの候補がありません
    p = link_to "投稿する", action: :post_theme

app/views/themes/index.html.slim
.theme-list
  - if @themes.present?
    ul.themes
      - @themes.each do |theme|
        li.theme
          .title
            p = theme.title
          .content
            p = theme.content
          .kind
            p = theme.kind
  - else
    | テーマの候補がないよー勉強会しようよー😩😩😩

app/views/themes/post_theme.html.slim
.theme-form
  h2 テーマ作成
  = form_for @theme do |f|
    p = f.text_field :title, size: '60', placeholder: 'タイトル'
    p = f.text_field :kind, size: '60', placeholder: 'タグ'
    p = f.text_area :content, size: '60x10', placeholder: '内容'
    p = f.submit "登録する"